/**
 * Script auxiliar — gera a migration 015_humanize_food_names.sql
 * com os nomes humanizados para os alimentos da tabela TACO.
 *
 * Uso:
 *   npx tsx src/database/scripts/generate-rename-migration.ts
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

function slugify(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 180);
}

// id → nome humanizado
const renames: Record<number, string> = {
  // ── Cereais e derivados ──────────────────────────────────────────────
  1:  'Arroz branco cozido',
  2:  'Arroz integral cozido',
  3:  'Batata inglesa cozida',
  4:  'Batata-doce cozida',
  5:  'Aipim cozido',
  6:  'Inhame cozido',
  7:  'Macarrão cozido',
  8:  'Arroz integral cru',
  9:  'Arroz tipo 1 cozido',
  10: 'Arroz tipo 1 cru',
  11: 'Arroz tipo 2 cozido',
  12: 'Arroz tipo 2 cru',
  13: 'Aveia em flocos crua',
  14: 'Biscoito maisena',
  15: 'Biscoito recheado de chocolate',
  16: 'Biscoito recheado de morango',
  17: 'Biscoito wafer recheado de chocolate',
  18: 'Biscoito wafer recheado de morango',
  19: 'Biscoito cream cracker',
  20: 'Mistura para bolo',
  21: 'Bolo de aipim',
  22: 'Bolo de chocolate',
  23: 'Bolo de coco',
  24: 'Bolo de milho',
  25: 'Canjica branca crua',
  26: 'Canjica com leite integral',
  27: 'Flocos de milho com sal',
  28: 'Flocos de milho sem sal',
  29: 'Mingau de milho infantil',
  30: 'Mistura para vitamina de trigo, cevada e aveia',
  31: 'Cereal matinal de milho',
  32: 'Cereal matinal de milho com açúcar',
  33: 'Creme de arroz em pó',
  34: 'Creme de milho em pó',
  35: 'Curau de milho verde',
  36: 'Mistura para curau de milho verde',
  37: 'Farinha de arroz enriquecida',
  38: 'Farinha de centeio integral',
  39: 'Farinha de milho amarela',
  40: 'Farinha de rosca',
  41: 'Farinha de trigo',
  42: 'Farinha láctea de cereais',
  43: 'Lasanha de massa fresca cozida',
  44: 'Lasanha de massa fresca crua',
  45: 'Macarrão instantâneo',
  46: 'Macarrão de trigo cru',
  47: 'Macarrão de trigo com ovos cru',
  48: 'Amido de milho',
  49: 'Fubá de milho',
  50: 'Milho verde cru',
  51: 'Milho verde enlatado drenado',
  52: 'Mingau tradicional em pó',
  53: 'Pamonha pré-cozida',
  54: 'Pão de aveia de forma',
  55: 'Pão de soja',
  56: 'Pão de glúten de forma',
  57: 'Pão de milho de forma',
  58: 'Pão integral de forma',
  59: 'Pão francês',
  60: 'Pão sovado',
  61: 'Pastel de carne cru',
  62: 'Pastel de carne frito',
  63: 'Pastel de queijo cru',
  64: 'Pastel de queijo frito',
  65: 'Massa de pastel crua',
  66: 'Massa de pastel frita',
  67: 'Pipoca com óleo de soja sem sal',
  68: 'Polenta pré-cozida',
  69: 'Torrada de pão francês',

  // ── Verduras, hortaliças e derivados ────────────────────────────────
  70:  'Abóbora cabotiá cozida',
  71:  'Abóbora cabotiá crua',
  72:  'Abóbora menina brasileira crua',
  73:  'Moranga crua',
  74:  'Moranga refogada',
  75:  'Abóbora pescoço crua',
  76:  'Abobrinha italiana cozida',
  77:  'Abobrinha italiana crua',
  78:  'Abobrinha italiana refogada',
  79:  'Abobrinha paulista crua',
  80:  'Acelga crua',
  81:  'Agrião cru',
  82:  'Aipo cru',
  83:  'Alface americana crua',
  84:  'Alface crespa crua',
  85:  'Alface lisa crua',
  86:  'Alface roxa crua',
  87:  'Alfavaca crua',
  88:  'Alho cru',
  89:  'Alho-poró cru',
  90:  'Almeirão cru',
  91:  'Almeirão refogado',
  92:  'Batata-baroa cozida',
  93:  'Batata-baroa crua',
  94:  'Batata-doce crua',
  95:  'Batata chips industrializada',
  96:  'Batata inglesa crua',
  97:  'Batata inglesa frita',
  98:  'Batata inglesa sauté',
  99:  'Berinjela cozida',
  100: 'Berinjela crua',
  101: 'Beterraba cozida',
  102: 'Beterraba crua',
  103: 'Biscoito de polvilho doce',
  104: 'Brócolis cozido',
  105: 'Brócolis cru',
  106: 'Cará cozido',
  107: 'Cará cru',
  108: 'Caruru cru',
  109: 'Catalonha crua',
  110: 'Catalonha refogada',
  111: 'Cebola crua',
  112: 'Cebolinha crua',
  113: 'Cenoura cozida',
  114: 'Cenoura crua',
  115: 'Chicória crua',
  116: 'Chuchu cozido',
  117: 'Chuchu cru',
  118: 'Coentro desidratado',
  119: 'Couve-manteiga crua',
  120: 'Couve-manteiga refogada',
  121: 'Couve-flor crua',
  122: 'Couve-flor cozida',
  123: 'Espinafre da nova zelândia cru',
  124: 'Espinafre da nova zelândia refogado',
  125: 'Farinha de mandioca crua',
  126: 'Farinha de mandioca torrada',
  127: 'Farinha de puba',
  128: 'Fécula de mandioca',
  129: 'Broto de feijão cru',
  130: 'Inhame cru',
  131: 'Jiló cru',
  132: 'Jurubeba crua',
  133: 'Mandioca cozida',
  134: 'Mandioca crua',
  135: 'Farofa de mandioca temperada',
  136: 'Mandioca frita',
  137: 'Manjericão cru',
  138: 'Maxixe cru',
  139: 'Folha de mostarda crua',
  140: 'Nhoque de batata cozido',
  141: 'Nabo cru',
  142: 'Palmito juçara em conserva',
  143: 'Palmito pupunha em conserva',
  144: 'Pão de queijo assado',
  145: 'Pão de queijo cru',
  146: 'Pepino cru',
  147: 'Pimentão amarelo cru',
  148: 'Pimentão verde cru',
  149: 'Pimentão vermelho cru',
  150: 'Polvilho doce',
  151: 'Quiabo cru',
  152: 'Rabanete cru',
  153: 'Repolho branco cru',
  154: 'Repolho roxo cru',
  155: 'Repolho roxo refogado',
  156: 'Rúcula crua',
  157: 'Salsa crua',
  158: 'Seleta de legumes enlatada',
  159: 'Serralha crua',
  160: 'Taioba crua',
  161: 'Tomate cru com semente',
  162: 'Extrato de tomate',
  163: 'Molho de tomate industrializado',
  164: 'Purê de tomate',
  165: 'Tomate para salada',
  166: 'Vagem crua',

  // ── Frutas e derivados ───────────────────────────────────────────────
  167: 'Abacate cru',
  168: 'Abacaxi cru',
  169: 'Polpa de abacaxi congelada',
  170: 'Abiu cru',
  171: 'Açaí com xarope de guaraná e glucose',
  172: 'Polpa de açaí congelada',
  173: 'Acerola crua',
  174: 'Polpa de acerola congelada',
  175: 'Ameixa em calda enlatada',
  176: 'Ameixa crua',
  177: 'Ameixa em calda enlatada drenada',
  178: 'Atemoia crua',
  179: 'Banana-da-terra crua',
  180: 'Banana em doce de barra',
  181: 'Banana-figo crua',
  182: 'Banana-maçã crua',
  183: 'Banana nanica crua',
  184: 'Banana-ouro crua',
  185: 'Banana-pacova crua',
  186: 'Banana-prata crua',
  187: 'Cacau cru',
  188: 'Cajá-manga cru',
  189: 'Polpa de cajá congelada',
  190: 'Caju cru',
  191: 'Polpa de caju congelada',
  192: 'Suco concentrado de caju envasado',
  193: 'Caqui chocolate cru',
  194: 'Carambola crua',
  195: 'Ciriguela crua',
  196: 'Cupuaçu cru',
  197: 'Polpa de cupuaçu congelada',
  198: 'Figo cru',
  199: 'Figo enlatado em calda',
  200: 'Fruta-pão crua',
  201: 'Goiaba branca com casca crua',
  202: 'Goiaba em doce de pasta',
  203: 'Cascão de goiaba',
  204: 'Goiaba vermelha com casca crua',
  208: 'Graviola crua',
  209: 'Polpa de graviola congelada',
  210: 'Jabuticaba crua',
  211: 'Jaca crua',
  212: 'Jambo cru',
  213: 'Jamelão cru',
  214: 'Kiwi cru',
  215: 'Laranja baía crua',
  216: 'Suco de laranja baía',
  217: 'Laranja-da-terra crua',
  218: 'Suco de laranja-da-terra',
  219: 'Laranja-lima crua',
  220: 'Suco de laranja-lima',
  221: 'Laranja-pêra crua',
  222: 'Suco de laranja-pêra',
  223: 'Laranja valência crua',
  224: 'Suco de laranja valência',
  225: 'Suco de limão cravo',
  226: 'Suco de limão galego',
  227: 'Limão tahiti cru',
  228: 'Maçã argentina com casca crua',
  229: 'Maçã fuji com casca crua',
  230: 'Macaúba crua',
  231: 'Mamão em doce de calda drenado',
  232: 'Mamão formosa cru',
  233: 'Mamão papaia cru',
  234: 'Mamão verde em doce de calda drenado',
  235: 'Manga haden crua',
  236: 'Manga palmer crua',
  237: 'Polpa de manga congelada',
  238: 'Manga tommy atkins crua',
  239: 'Maracujá cru',
  240: 'Polpa de maracujá congelada',
  241: 'Suco concentrado de maracujá envasado',
  242: 'Melancia crua',
  243: 'Melão cru',
  244: 'Mexerica murcote crua',
  245: 'Mexerica rio crua',
  246: 'Morango cru',
  247: 'Nêspera crua',
  248: 'Pequi cru',
  249: 'Pêra park crua',
  250: 'Pêra williams crua',
  251: 'Pêssego aurora cru',
  252: 'Pêssego enlatado em calda',
  253: 'Pinha crua',
  254: 'Pitanga crua',
  255: 'Polpa de pitanga congelada',
  256: 'Romã crua',
  257: 'Tamarindo cru',
  258: 'Tangerina poncã crua',
  259: 'Suco de tangerina poncã',
  260: 'Tucumã cru',
  261: 'Umbu cru',
  262: 'Polpa de umbu congelada',
  263: 'Uva itália crua',
  264: 'Uva rubi crua',
  265: 'Suco concentrado de uva envasado',

  // ── Gorduras e óleos ─────────────────────────────────────────────────
  266: 'Azeite de dendê',
  267: 'Azeite de oliva extra virgem',
  268: 'Manteiga com sal',
  269: 'Manteiga sem sal',
  270: 'Margarina com sal 65% lipídeos (óleo hidrogenado)',
  271: 'Margarina sem sal 80% lipídeos (óleo hidrogenado)',
  272: 'Margarina com sal 65% lipídeos (óleo interesterificado)',
  273: 'Margarina sem sal 65% lipídeos (óleo interesterificado)',
  274: 'Óleo de babaçu',
  275: 'Óleo de canola',
  276: 'Óleo de girassol',
  277: 'Óleo de milho',
  278: 'Óleo de pequi',
  279: 'Óleo de soja',

  // ── Pescados e frutos do mar ──────────────────────────────────────────
  280: 'Filé de abadejo congelado assado',
  281: 'Filé de abadejo congelado cozido',
  282: 'Filé de abadejo congelado cru',
  283: 'Filé de abadejo congelado grelhado',
  284: 'Atum em conserva no óleo',
  285: 'Atum fresco cru',
  286: 'Bacalhau salgado cru',
  287: 'Bacalhau salgado refogado',
  288: 'Posta de cação frita com farinha de trigo',
  289: 'Posta de cação cozida',
  290: 'Posta de cação crua',
  291: 'Camarão rio grande cozido',
  292: 'Camarão rio grande cru',
  293: 'Camarão sete barbas frito sem cabeça com casca',
  294: 'Caranguejo cozido',
  295: 'Corimba cru',
  296: 'Corimbatá assado',
  297: 'Corimbatá cozido',
  298: 'Corvina de água doce crua',
  299: 'Corvina do mar crua',
  300: 'Corvina grande assada',
  301: 'Corvina grande cozida',
  302: 'Dourado de água doce fresco',
  303: 'Lambari congelado cru',
  304: 'Lambari congelado frito',
  305: 'Lambari fresco cru',
  306: 'Manjuba frita com farinha de trigo',
  307: 'Manjuba frita',
  308: 'Filé de merluza assado',
  309: 'Filé de merluza cru',
  310: 'Filé de merluza frito',
  311: 'Pescada branca crua',
  312: 'Pescada branca frita',
  313: 'Filé de pescada frito com farinha de trigo',
  314: 'Filé de pescada cru',
  315: 'Filé de pescada frito',
  316: 'Filé de pescada ao escabeche',
  317: 'Pescadinha crua',
  318: 'Pintado assado',
  319: 'Pintado cru',
  320: 'Pintado grelhado',
  321: 'Porquinho cru',
  322: 'Filé de salmão grelhado com pele',
  323: 'Salmão fresco cru sem pele',
  324: 'Salmão fresco grelhado sem pele',
  325: 'Sardinha assada',
  326: 'Sardinha em conserva no óleo',
  327: 'Sardinha frita',
  328: 'Sardinha inteira crua',
  329: 'Filé de tucunaré congelado cru',

  // ── Carnes e derivados ───────────────────────────────────────────────
  330: 'Apresuntado',
  331: 'Caldo de carne em tablete',
  332: 'Caldo de galinha em tablete',
  333: 'Acém bovino moído cozido',
  334: 'Acém bovino moído cru',
  335: 'Acém bovino sem gordura cozido',
  336: 'Acém bovino sem gordura cru',
  337: 'Almôndegas bovinas cruas',
  338: 'Almôndegas bovinas fritas',
  339: 'Bucho bovino cozido',
  340: 'Bucho bovino cru',
  341: 'Capa de contra-filé com gordura crua',
  342: 'Capa de contra-filé com gordura grelhada',
  343: 'Capa de contra-filé sem gordura crua',
  344: 'Capa de contra-filé sem gordura grelhada',
  345: 'Charque bovino cozido',
  346: 'Charque bovino cru',
  347: 'Contra-filé bovino à milanesa',
  348: 'Contra-filé de costela bovino cru',
  349: 'Contra-filé de costela bovino grelhado',
  350: 'Contra-filé bovino com gordura cru',
  351: 'Contra-filé bovino com gordura grelhado',
  352: 'Contra-filé bovino sem gordura cru',
  353: 'Contra-filé bovino sem gordura grelhado',
  354: 'Costela bovina assada',
  355: 'Costela bovina crua',
  356: 'Coxão duro bovino sem gordura cozido',
  357: 'Coxão duro bovino sem gordura cru',
  358: 'Coxão mole bovino sem gordura cozido',
  359: 'Coxão mole bovino sem gordura cru',
  360: 'Cupim bovino assado',
  361: 'Cupim bovino cru',
  362: 'Fígado bovino cru',
  363: 'Fígado bovino grelhado',
  364: 'Filé mignon bovino sem gordura cru',
  365: 'Filé mignon bovino sem gordura grelhado',
  366: 'Flanco bovino sem gordura cozido',
  367: 'Flanco bovino sem gordura cru',
  368: 'Fraldinha bovina com gordura cozida',
  369: 'Fraldinha bovina com gordura crua',
  370: 'Lagarto bovino cozido',
  371: 'Lagarto bovino cru',
  372: 'Língua bovina cozida',
  373: 'Língua bovina crua',
  374: 'Maminha bovina crua',
  375: 'Maminha bovina grelhada',
  376: 'Miolo de alcatra bovino sem gordura cru',
  377: 'Miolo de alcatra bovino sem gordura grelhado',
  378: 'Músculo bovino sem gordura cozido',
  379: 'Músculo bovino sem gordura cru',
  380: 'Paleta bovina com gordura crua',
  381: 'Paleta bovina sem gordura cozida',
  382: 'Paleta bovina sem gordura crua',
  383: 'Patinho bovino sem gordura cru',
  384: 'Patinho bovino sem gordura grelhado',
  385: 'Peito bovino sem gordura cozido',
  386: 'Peito bovino sem gordura cru',
  387: 'Picanha bovina com gordura crua',
  388: 'Picanha bovina com gordura grelhada',
  389: 'Picanha bovina sem gordura crua',
  390: 'Picanha bovina sem gordura grelhada',
  391: 'Carne seca bovina cozida',
  392: 'Carne seca bovina crua',
  393: 'Coxinha de frango frita',
  394: 'Croquete de carne cru',
  395: 'Croquete de carne frito',
  396: 'Empada de frango assada',
  397: 'Empada de frango pré-cozida',
  398: 'Asa de frango com pele crua',
  399: 'Frango caipira inteiro com pele cozido',
  400: 'Frango caipira inteiro sem pele cozido',
  401: 'Coração de frango cru',
  402: 'Coração de frango grelhado',
  403: 'Coxa de frango com pele assada',
  404: 'Coxa de frango com pele crua',
  405: 'Coxa de frango sem pele cozida',
  406: 'Coxa de frango sem pele crua',
  407: 'Fígado de frango cru',
  408: 'Filé de frango à milanesa',
  409: 'Frango inteiro com pele cru',
  410: 'Frango inteiro sem pele assado',
  411: 'Frango inteiro sem pele cozido',
  412: 'Frango inteiro sem pele cru',
  413: 'Peito de frango com pele assado',
  414: 'Peito de frango com pele cru',
  415: 'Peito de frango sem pele cozido',
  416: 'Peito de frango sem pele cru',
  417: 'Peito de frango sem pele grelhado',
  418: 'Sobrecoxa de frango com pele assada',
  419: 'Sobrecoxa de frango com pele crua',
  420: 'Sobrecoxa de frango sem pele assada',
  421: 'Sobrecoxa de frango sem pele crua',
  422: 'Hambúrguer bovino cru',
  423: 'Hambúrguer bovino frito',
  424: 'Hambúrguer bovino grelhado',
  425: 'Linguiça de frango crua',
  426: 'Linguiça de frango frita',
  427: 'Linguiça de frango grelhada',
  428: 'Linguiça de porco crua',
  429: 'Linguiça de porco frita',
  430: 'Linguiça de porco grelhada',
  431: 'Mortadela',
  432: 'Peru congelado assado',
  433: 'Peru congelado cru',
  434: 'Bisteca de porco crua',
  435: 'Bisteca de porco frita',
  436: 'Bisteca de porco grelhada',
  437: 'Costela de porco assada',
  438: 'Costela de porco crua',
  439: 'Lombo de porco assado',
  440: 'Lombo de porco cru',
  441: 'Orelha de porco salgada crua',
  442: 'Pernil de porco assado',
  443: 'Pernil de porco cru',
  444: 'Rabo de porco salgado cru',
  445: 'Presunto com capa de gordura',
  446: 'Presunto sem capa de gordura',
  447: 'Quibe assado',
  448: 'Quibe cru',
  449: 'Quibe frito',
  450: 'Salame',
  451: 'Toucinho cru',
  452: 'Toucinho frito',

  // ── Leite e derivados ────────────────────────────────────────────────
  453: 'Bebida láctea de pêssego',
  454: 'Creme de leite',
  455: 'Iogurte natural',
  456: 'Iogurte natural desnatado',
  457: 'Iogurte sabor morango',
  458: 'Iogurte sabor pêssego',
  459: 'Leite condensado',
  460: 'Leite de cabra',
  461: 'Leite achocolatado',
  462: 'Leite de vaca desnatado em pó',
  463: 'Leite de vaca integral em pó',
  464: 'Leite fermentado',
  465: 'Queijo minas frescal',
  466: 'Queijo minas meia cura',
  467: 'Queijo mozarela',
  468: 'Queijo parmesão',
  469: 'Queijo pasteurizado',
  470: 'Queijo petit suisse de morango',
  471: 'Queijo prato',
  472: 'Requeijão cremoso',
  473: 'Ricota',

  // ── Bebidas ──────────────────────────────────────────────────────────
  474: 'Bebida isotônica',
  475: 'Café infusão 10%',
  476: 'Aguardente de cana',
  477: 'Caldo de cana',
  478: 'Cerveja pilsen',
  479: 'Chá de erva-doce',
  480: 'Chá mate',
  481: 'Chá preto',
  482: 'Água de coco',
  483: 'Refrigerante água tônica',
  484: 'Refrigerante tipo cola',
  485: 'Refrigerante guaraná',
  486: 'Refrigerante laranja',
  487: 'Refrigerante limão',

  // ── Ovos e derivados ─────────────────────────────────────────────────
  488: 'Omelete de queijo',
  489: 'Ovo de codorna inteiro cru',
  490: 'Clara de ovo de galinha cozida',
  491: 'Gema de ovo de galinha cozida',
  492: 'Ovo de galinha inteiro cozido',
  493: 'Ovo de galinha inteiro cru',
  494: 'Ovo de galinha frito',

  // ── Açúcares e doces ─────────────────────────────────────────────────
  495: 'Achocolatado em pó',
  496: 'Açúcar cristal',
  497: 'Açúcar mascavo',
  498: 'Açúcar refinado',
  499: 'Chocolate ao leite',
  500: 'Chocolate ao leite com castanha do pará',
  501: 'Chocolate ao leite dietético',
  502: 'Chocolate meio amargo',
  503: 'Cocada branca',
  504: 'Doce de abóbora cremoso',
  505: 'Doce de leite cremoso',
  506: 'Geleia de mocotó natural',
  507: 'Glicose de milho',
  508: 'Maria mole',
  509: 'Maria mole de coco queimado',
  510: 'Marmelada',
  511: 'Mel de abelha',
  512: 'Melado',
  513: 'Quindim',
  514: 'Rapadura',

  // ── Molhos e industrializados ─────────────────────────────────────────
  515: 'Café em pó torrado',
  516: 'Cappuccino em pó',
  517: 'Fermento em pó químico',
  518: 'Fermento biológico em tablete',
  519: 'Gelatina em pó sabores variados',
  520: 'Shoyu',
  521: 'Tempero à base de sal',
  522: 'Azeitona preta em conserva',
  523: 'Azeitona verde em conserva',
  524: 'Chantilly em spray com gordura vegetal',
  525: 'Leite de coco',
  526: 'Maionese tradicional com ovos',

  // ── Pratos típicos ────────────────────────────────────────────────────
  527: 'Acarajé',
  528: 'Arroz carreteiro',
  529: 'Baião de dois',
  530: 'Barreado',
  531: 'Bife à cavalo com contra-filé',
  532: 'Bolinho de arroz',
  533: 'Camarão à baiana',
  534: 'Charuto de repolho',
  535: 'Cuscuz de milho cozido com sal',
  536: 'Cuscuz paulista',
  537: 'Molho cuxá',
  538: 'Dobradinha',
  539: 'Estrogonofe de carne',
  540: 'Estrogonofe de frango',
  541: 'Feijão tropeiro mineiro',
  543: 'Frango com açafrão',
  544: 'Macarrão ao molho bolognesa',
  545: 'Maniçoba',
  546: 'Quibebe',
  547: 'Salada de legumes com maionese',
  548: 'Salada de legumes cozida no vapor',
  549: 'Salpicão de frango',
  550: 'Sarapatel',
  551: 'Tabule',
  552: 'Tacacá',
  553: 'Tapioca com manteiga',
  554: 'Tucupi com pimenta-de-cheiro',
  555: 'Vaca atolada',
  556: 'Vatapá',
  557: 'Virado à paulista',
  558: 'Yakisoba',

  // ── Leguminosas e derivados ───────────────────────────────────────────
  559: 'Amendoim em grão cru',
  560: 'Amendoim torrado salgado',
  561: 'Ervilha em vagem',
  562: 'Ervilha enlatada drenada',
  563: 'Feijão carioca cozido',
  564: 'Feijão carioca cru',
  565: 'Feijão fradinho cozido',
  566: 'Feijão fradinho cru',
  567: 'Feijão jalo cozido',
  568: 'Feijão jalo cru',
  569: 'Feijão preto cozido',
  570: 'Feijão preto cru',
  571: 'Feijão rajado cozido',
  572: 'Feijão rajado cru',
  573: 'Feijão rosinha cozido',
  574: 'Feijão rosinha cru',
  575: 'Feijão roxo cozido',
  576: 'Feijão roxo cru',
  577: 'Grão-de-bico cru',
  578: 'Guandu cru',
  579: 'Lentilha cozida',
  580: 'Lentilha crua',
  581: 'Paçoca de amendoim',
  582: 'Pé-de-moleque de amendoim',
  583: 'Farinha de soja',
  584: 'Extrato de soja natural fluido',
  585: 'Extrato de soja em pó',
  586: 'Tofu',
  587: 'Tremoço cru',
  588: 'Tremoço em conserva',

  // ── Nozes e sementes ──────────────────────────────────────────────────
  589: 'Amêndoa torrada salgada',
  590: 'Castanha de caju torrada salgada',
  591: 'Castanha-do-pará crua',
  592: 'Coco cru',
  593: 'Farinha de mesocarpo de babaçu crua',
  594: 'Semente de gergelim',
  595: 'Semente de linhaça',
  596: 'Pinhão cozido',
  597: 'Pupunha cozida',
  598: 'Noz crua',
};

// Verifica slugs duplicados antes de gerar
function checkDuplicateSlugs(map: Record<number, string>): void {
  const slugToId = new Map<string, number>();
  const duplicates: string[] = [];

  for (const [id, name] of Object.entries(map)) {
    const slug = slugify(name);
    const existingId = slugToId.get(slug);

    if (existingId !== undefined) {
      duplicates.push(`  Slug "${slug}" duplicado: id ${existingId} e id ${id} ("${name}")`);
    } else {
      slugToId.set(slug, Number(id));
    }
  }

  if (duplicates.length > 0) {
    console.error('ERRO: Slugs duplicados detectados:');
    duplicates.forEach((msg) => console.error(msg));
    process.exit(1);
  }
}

function escape(value: string): string {
  return value.replace(/'/g, "''");
}

function generateSql(map: Record<number, string>): string {
  const lines: string[] = [
    '-- Migration: 015_humanize_food_names',
    '-- Renomeia os alimentos da TACO para nomes mais naturais ao cotidiano brasileiro.',
    '-- Gerado por: src/database/scripts/generate-rename-migration.ts',
    '',
    'START TRANSACTION;',
    ''
  ];

  for (const [rawId, name] of Object.entries(map)) {
    const id = Number(rawId);
    const slug = slugify(name);
    const safeName = escape(name);
    const safeSlug = escape(slug);
    lines.push(`UPDATE foods SET name = '${safeName}', slug = '${safeSlug}' WHERE id = ${id};`);
  }

  lines.push('');
  lines.push('COMMIT;');
  lines.push('');

  return lines.join('\n');
}

checkDuplicateSlugs(renames);

const sql = generateSql(renames);
const outputPath = resolve(
  __dirname,
  '../../db/migrations/015_humanize_food_names.sql'
);

writeFileSync(outputPath, sql, 'utf8');

const count = Object.keys(renames).length;
console.log(`✓ Migration gerada: ${outputPath}`);
console.log(`  Alimentos renomeados: ${count}`);
