-- Migration: 015_humanize_food_names
-- Renomeia os alimentos da TACO para nomes mais naturais ao cotidiano brasileiro.
-- Gerado por: src/database/scripts/generate-rename-migration.ts

START TRANSACTION;

UPDATE foods SET name = 'Arroz branco cozido', slug = 'arroz-branco-cozido' WHERE id = 1;
UPDATE foods SET name = 'Arroz integral cozido', slug = 'arroz-integral-cozido' WHERE id = 2;
UPDATE foods SET name = 'Batata inglesa cozida', slug = 'batata-inglesa-cozida' WHERE id = 3;
UPDATE foods SET name = 'Batata-doce cozida', slug = 'batata-doce-cozida' WHERE id = 4;
UPDATE foods SET name = 'Aipim cozido', slug = 'aipim-cozido' WHERE id = 5;
UPDATE foods SET name = 'Inhame cozido', slug = 'inhame-cozido' WHERE id = 6;
UPDATE foods SET name = 'Macarrão cozido', slug = 'macarrao-cozido' WHERE id = 7;
UPDATE foods SET name = 'Arroz integral cru', slug = 'arroz-integral-cru' WHERE id = 8;
UPDATE foods SET name = 'Arroz tipo 1 cozido', slug = 'arroz-tipo-1-cozido' WHERE id = 9;
UPDATE foods SET name = 'Arroz tipo 1 cru', slug = 'arroz-tipo-1-cru' WHERE id = 10;
UPDATE foods SET name = 'Arroz tipo 2 cozido', slug = 'arroz-tipo-2-cozido' WHERE id = 11;
UPDATE foods SET name = 'Arroz tipo 2 cru', slug = 'arroz-tipo-2-cru' WHERE id = 12;
UPDATE foods SET name = 'Aveia em flocos crua', slug = 'aveia-em-flocos-crua' WHERE id = 13;
UPDATE foods SET name = 'Biscoito maisena', slug = 'biscoito-maisena' WHERE id = 14;
UPDATE foods SET name = 'Biscoito recheado de chocolate', slug = 'biscoito-recheado-de-chocolate' WHERE id = 15;
UPDATE foods SET name = 'Biscoito recheado de morango', slug = 'biscoito-recheado-de-morango' WHERE id = 16;
UPDATE foods SET name = 'Biscoito wafer recheado de chocolate', slug = 'biscoito-wafer-recheado-de-chocolate' WHERE id = 17;
UPDATE foods SET name = 'Biscoito wafer recheado de morango', slug = 'biscoito-wafer-recheado-de-morango' WHERE id = 18;
UPDATE foods SET name = 'Biscoito cream cracker', slug = 'biscoito-cream-cracker' WHERE id = 19;
UPDATE foods SET name = 'Mistura para bolo', slug = 'mistura-para-bolo' WHERE id = 20;
UPDATE foods SET name = 'Bolo de aipim', slug = 'bolo-de-aipim' WHERE id = 21;
UPDATE foods SET name = 'Bolo de chocolate', slug = 'bolo-de-chocolate' WHERE id = 22;
UPDATE foods SET name = 'Bolo de coco', slug = 'bolo-de-coco' WHERE id = 23;
UPDATE foods SET name = 'Bolo de milho', slug = 'bolo-de-milho' WHERE id = 24;
UPDATE foods SET name = 'Canjica branca crua', slug = 'canjica-branca-crua' WHERE id = 25;
UPDATE foods SET name = 'Canjica com leite integral', slug = 'canjica-com-leite-integral' WHERE id = 26;
UPDATE foods SET name = 'Flocos de milho com sal', slug = 'flocos-de-milho-com-sal' WHERE id = 27;
UPDATE foods SET name = 'Flocos de milho sem sal', slug = 'flocos-de-milho-sem-sal' WHERE id = 28;
UPDATE foods SET name = 'Mingau de milho infantil', slug = 'mingau-de-milho-infantil' WHERE id = 29;
UPDATE foods SET name = 'Mistura para vitamina de trigo, cevada e aveia', slug = 'mistura-para-vitamina-de-trigo-cevada-e-aveia' WHERE id = 30;
UPDATE foods SET name = 'Cereal matinal de milho', slug = 'cereal-matinal-de-milho' WHERE id = 31;
UPDATE foods SET name = 'Cereal matinal de milho com açúcar', slug = 'cereal-matinal-de-milho-com-acucar' WHERE id = 32;
UPDATE foods SET name = 'Creme de arroz em pó', slug = 'creme-de-arroz-em-po' WHERE id = 33;
UPDATE foods SET name = 'Creme de milho em pó', slug = 'creme-de-milho-em-po' WHERE id = 34;
UPDATE foods SET name = 'Curau de milho verde', slug = 'curau-de-milho-verde' WHERE id = 35;
UPDATE foods SET name = 'Mistura para curau de milho verde', slug = 'mistura-para-curau-de-milho-verde' WHERE id = 36;
UPDATE foods SET name = 'Farinha de arroz enriquecida', slug = 'farinha-de-arroz-enriquecida' WHERE id = 37;
UPDATE foods SET name = 'Farinha de centeio integral', slug = 'farinha-de-centeio-integral' WHERE id = 38;
UPDATE foods SET name = 'Farinha de milho amarela', slug = 'farinha-de-milho-amarela' WHERE id = 39;
UPDATE foods SET name = 'Farinha de rosca', slug = 'farinha-de-rosca' WHERE id = 40;
UPDATE foods SET name = 'Farinha de trigo', slug = 'farinha-de-trigo' WHERE id = 41;
UPDATE foods SET name = 'Farinha láctea de cereais', slug = 'farinha-lactea-de-cereais' WHERE id = 42;
UPDATE foods SET name = 'Lasanha de massa fresca cozida', slug = 'lasanha-de-massa-fresca-cozida' WHERE id = 43;
UPDATE foods SET name = 'Lasanha de massa fresca crua', slug = 'lasanha-de-massa-fresca-crua' WHERE id = 44;
UPDATE foods SET name = 'Macarrão instantâneo', slug = 'macarrao-instantaneo' WHERE id = 45;
UPDATE foods SET name = 'Macarrão de trigo cru', slug = 'macarrao-de-trigo-cru' WHERE id = 46;
UPDATE foods SET name = 'Macarrão de trigo com ovos cru', slug = 'macarrao-de-trigo-com-ovos-cru' WHERE id = 47;
UPDATE foods SET name = 'Amido de milho', slug = 'amido-de-milho' WHERE id = 48;
UPDATE foods SET name = 'Fubá de milho', slug = 'fuba-de-milho' WHERE id = 49;
UPDATE foods SET name = 'Milho verde cru', slug = 'milho-verde-cru' WHERE id = 50;
UPDATE foods SET name = 'Milho verde enlatado drenado', slug = 'milho-verde-enlatado-drenado' WHERE id = 51;
UPDATE foods SET name = 'Mingau tradicional em pó', slug = 'mingau-tradicional-em-po' WHERE id = 52;
UPDATE foods SET name = 'Pamonha pré-cozida', slug = 'pamonha-pre-cozida' WHERE id = 53;
UPDATE foods SET name = 'Pão de aveia de forma', slug = 'pao-de-aveia-de-forma' WHERE id = 54;
UPDATE foods SET name = 'Pão de soja', slug = 'pao-de-soja' WHERE id = 55;
UPDATE foods SET name = 'Pão de glúten de forma', slug = 'pao-de-gluten-de-forma' WHERE id = 56;
UPDATE foods SET name = 'Pão de milho de forma', slug = 'pao-de-milho-de-forma' WHERE id = 57;
UPDATE foods SET name = 'Pão integral de forma', slug = 'pao-integral-de-forma' WHERE id = 58;
UPDATE foods SET name = 'Pão francês', slug = 'pao-frances' WHERE id = 59;
UPDATE foods SET name = 'Pão sovado', slug = 'pao-sovado' WHERE id = 60;
UPDATE foods SET name = 'Pastel de carne cru', slug = 'pastel-de-carne-cru' WHERE id = 61;
UPDATE foods SET name = 'Pastel de carne frito', slug = 'pastel-de-carne-frito' WHERE id = 62;
UPDATE foods SET name = 'Pastel de queijo cru', slug = 'pastel-de-queijo-cru' WHERE id = 63;
UPDATE foods SET name = 'Pastel de queijo frito', slug = 'pastel-de-queijo-frito' WHERE id = 64;
UPDATE foods SET name = 'Massa de pastel crua', slug = 'massa-de-pastel-crua' WHERE id = 65;
UPDATE foods SET name = 'Massa de pastel frita', slug = 'massa-de-pastel-frita' WHERE id = 66;
UPDATE foods SET name = 'Pipoca com óleo de soja sem sal', slug = 'pipoca-com-oleo-de-soja-sem-sal' WHERE id = 67;
UPDATE foods SET name = 'Polenta pré-cozida', slug = 'polenta-pre-cozida' WHERE id = 68;
UPDATE foods SET name = 'Torrada de pão francês', slug = 'torrada-de-pao-frances' WHERE id = 69;
UPDATE foods SET name = 'Abóbora cabotiá cozida', slug = 'abobora-cabotia-cozida' WHERE id = 70;
UPDATE foods SET name = 'Abóbora cabotiá crua', slug = 'abobora-cabotia-crua' WHERE id = 71;
UPDATE foods SET name = 'Abóbora menina brasileira crua', slug = 'abobora-menina-brasileira-crua' WHERE id = 72;
UPDATE foods SET name = 'Moranga crua', slug = 'moranga-crua' WHERE id = 73;
UPDATE foods SET name = 'Moranga refogada', slug = 'moranga-refogada' WHERE id = 74;
UPDATE foods SET name = 'Abóbora pescoço crua', slug = 'abobora-pescoco-crua' WHERE id = 75;
UPDATE foods SET name = 'Abobrinha italiana cozida', slug = 'abobrinha-italiana-cozida' WHERE id = 76;
UPDATE foods SET name = 'Abobrinha italiana crua', slug = 'abobrinha-italiana-crua' WHERE id = 77;
UPDATE foods SET name = 'Abobrinha italiana refogada', slug = 'abobrinha-italiana-refogada' WHERE id = 78;
UPDATE foods SET name = 'Abobrinha paulista crua', slug = 'abobrinha-paulista-crua' WHERE id = 79;
UPDATE foods SET name = 'Acelga crua', slug = 'acelga-crua' WHERE id = 80;
UPDATE foods SET name = 'Agrião cru', slug = 'agriao-cru' WHERE id = 81;
UPDATE foods SET name = 'Aipo cru', slug = 'aipo-cru' WHERE id = 82;
UPDATE foods SET name = 'Alface americana crua', slug = 'alface-americana-crua' WHERE id = 83;
UPDATE foods SET name = 'Alface crespa crua', slug = 'alface-crespa-crua' WHERE id = 84;
UPDATE foods SET name = 'Alface lisa crua', slug = 'alface-lisa-crua' WHERE id = 85;
UPDATE foods SET name = 'Alface roxa crua', slug = 'alface-roxa-crua' WHERE id = 86;
UPDATE foods SET name = 'Alfavaca crua', slug = 'alfavaca-crua' WHERE id = 87;
UPDATE foods SET name = 'Alho cru', slug = 'alho-cru' WHERE id = 88;
UPDATE foods SET name = 'Alho-poró cru', slug = 'alho-poro-cru' WHERE id = 89;
UPDATE foods SET name = 'Almeirão cru', slug = 'almeirao-cru' WHERE id = 90;
UPDATE foods SET name = 'Almeirão refogado', slug = 'almeirao-refogado' WHERE id = 91;
UPDATE foods SET name = 'Batata-baroa cozida', slug = 'batata-baroa-cozida' WHERE id = 92;
UPDATE foods SET name = 'Batata-baroa crua', slug = 'batata-baroa-crua' WHERE id = 93;
UPDATE foods SET name = 'Batata-doce crua', slug = 'batata-doce-crua' WHERE id = 94;
UPDATE foods SET name = 'Batata chips industrializada', slug = 'batata-chips-industrializada' WHERE id = 95;
UPDATE foods SET name = 'Batata inglesa crua', slug = 'batata-inglesa-crua' WHERE id = 96;
UPDATE foods SET name = 'Batata inglesa frita', slug = 'batata-inglesa-frita' WHERE id = 97;
UPDATE foods SET name = 'Batata inglesa sauté', slug = 'batata-inglesa-saute' WHERE id = 98;
UPDATE foods SET name = 'Berinjela cozida', slug = 'berinjela-cozida' WHERE id = 99;
UPDATE foods SET name = 'Berinjela crua', slug = 'berinjela-crua' WHERE id = 100;
UPDATE foods SET name = 'Beterraba cozida', slug = 'beterraba-cozida' WHERE id = 101;
UPDATE foods SET name = 'Beterraba crua', slug = 'beterraba-crua' WHERE id = 102;
UPDATE foods SET name = 'Biscoito de polvilho doce', slug = 'biscoito-de-polvilho-doce' WHERE id = 103;
UPDATE foods SET name = 'Brócolis cozido', slug = 'brocolis-cozido' WHERE id = 104;
UPDATE foods SET name = 'Brócolis cru', slug = 'brocolis-cru' WHERE id = 105;
UPDATE foods SET name = 'Cará cozido', slug = 'cara-cozido' WHERE id = 106;
UPDATE foods SET name = 'Cará cru', slug = 'cara-cru' WHERE id = 107;
UPDATE foods SET name = 'Caruru cru', slug = 'caruru-cru' WHERE id = 108;
UPDATE foods SET name = 'Catalonha crua', slug = 'catalonha-crua' WHERE id = 109;
UPDATE foods SET name = 'Catalonha refogada', slug = 'catalonha-refogada' WHERE id = 110;
UPDATE foods SET name = 'Cebola crua', slug = 'cebola-crua' WHERE id = 111;
UPDATE foods SET name = 'Cebolinha crua', slug = 'cebolinha-crua' WHERE id = 112;
UPDATE foods SET name = 'Cenoura cozida', slug = 'cenoura-cozida' WHERE id = 113;
UPDATE foods SET name = 'Cenoura crua', slug = 'cenoura-crua' WHERE id = 114;
UPDATE foods SET name = 'Chicória crua', slug = 'chicoria-crua' WHERE id = 115;
UPDATE foods SET name = 'Chuchu cozido', slug = 'chuchu-cozido' WHERE id = 116;
UPDATE foods SET name = 'Chuchu cru', slug = 'chuchu-cru' WHERE id = 117;
UPDATE foods SET name = 'Coentro desidratado', slug = 'coentro-desidratado' WHERE id = 118;
UPDATE foods SET name = 'Couve-manteiga crua', slug = 'couve-manteiga-crua' WHERE id = 119;
UPDATE foods SET name = 'Couve-manteiga refogada', slug = 'couve-manteiga-refogada' WHERE id = 120;
UPDATE foods SET name = 'Couve-flor crua', slug = 'couve-flor-crua' WHERE id = 121;
UPDATE foods SET name = 'Couve-flor cozida', slug = 'couve-flor-cozida' WHERE id = 122;
UPDATE foods SET name = 'Espinafre da nova zelândia cru', slug = 'espinafre-da-nova-zelandia-cru' WHERE id = 123;
UPDATE foods SET name = 'Espinafre da nova zelândia refogado', slug = 'espinafre-da-nova-zelandia-refogado' WHERE id = 124;
UPDATE foods SET name = 'Farinha de mandioca crua', slug = 'farinha-de-mandioca-crua' WHERE id = 125;
UPDATE foods SET name = 'Farinha de mandioca torrada', slug = 'farinha-de-mandioca-torrada' WHERE id = 126;
UPDATE foods SET name = 'Farinha de puba', slug = 'farinha-de-puba' WHERE id = 127;
UPDATE foods SET name = 'Fécula de mandioca', slug = 'fecula-de-mandioca' WHERE id = 128;
UPDATE foods SET name = 'Broto de feijão cru', slug = 'broto-de-feijao-cru' WHERE id = 129;
UPDATE foods SET name = 'Inhame cru', slug = 'inhame-cru' WHERE id = 130;
UPDATE foods SET name = 'Jiló cru', slug = 'jilo-cru' WHERE id = 131;
UPDATE foods SET name = 'Jurubeba crua', slug = 'jurubeba-crua' WHERE id = 132;
UPDATE foods SET name = 'Mandioca cozida', slug = 'mandioca-cozida' WHERE id = 133;
UPDATE foods SET name = 'Mandioca crua', slug = 'mandioca-crua' WHERE id = 134;
UPDATE foods SET name = 'Farofa de mandioca temperada', slug = 'farofa-de-mandioca-temperada' WHERE id = 135;
UPDATE foods SET name = 'Mandioca frita', slug = 'mandioca-frita' WHERE id = 136;
UPDATE foods SET name = 'Manjericão cru', slug = 'manjericao-cru' WHERE id = 137;
UPDATE foods SET name = 'Maxixe cru', slug = 'maxixe-cru' WHERE id = 138;
UPDATE foods SET name = 'Folha de mostarda crua', slug = 'folha-de-mostarda-crua' WHERE id = 139;
UPDATE foods SET name = 'Nhoque de batata cozido', slug = 'nhoque-de-batata-cozido' WHERE id = 140;
UPDATE foods SET name = 'Nabo cru', slug = 'nabo-cru' WHERE id = 141;
UPDATE foods SET name = 'Palmito juçara em conserva', slug = 'palmito-jucara-em-conserva' WHERE id = 142;
UPDATE foods SET name = 'Palmito pupunha em conserva', slug = 'palmito-pupunha-em-conserva' WHERE id = 143;
UPDATE foods SET name = 'Pão de queijo assado', slug = 'pao-de-queijo-assado' WHERE id = 144;
UPDATE foods SET name = 'Pão de queijo cru', slug = 'pao-de-queijo-cru' WHERE id = 145;
UPDATE foods SET name = 'Pepino cru', slug = 'pepino-cru' WHERE id = 146;
UPDATE foods SET name = 'Pimentão amarelo cru', slug = 'pimentao-amarelo-cru' WHERE id = 147;
UPDATE foods SET name = 'Pimentão verde cru', slug = 'pimentao-verde-cru' WHERE id = 148;
UPDATE foods SET name = 'Pimentão vermelho cru', slug = 'pimentao-vermelho-cru' WHERE id = 149;
UPDATE foods SET name = 'Polvilho doce', slug = 'polvilho-doce' WHERE id = 150;
UPDATE foods SET name = 'Quiabo cru', slug = 'quiabo-cru' WHERE id = 151;
UPDATE foods SET name = 'Rabanete cru', slug = 'rabanete-cru' WHERE id = 152;
UPDATE foods SET name = 'Repolho branco cru', slug = 'repolho-branco-cru' WHERE id = 153;
UPDATE foods SET name = 'Repolho roxo cru', slug = 'repolho-roxo-cru' WHERE id = 154;
UPDATE foods SET name = 'Repolho roxo refogado', slug = 'repolho-roxo-refogado' WHERE id = 155;
UPDATE foods SET name = 'Rúcula crua', slug = 'rucula-crua' WHERE id = 156;
UPDATE foods SET name = 'Salsa crua', slug = 'salsa-crua' WHERE id = 157;
UPDATE foods SET name = 'Seleta de legumes enlatada', slug = 'seleta-de-legumes-enlatada' WHERE id = 158;
UPDATE foods SET name = 'Serralha crua', slug = 'serralha-crua' WHERE id = 159;
UPDATE foods SET name = 'Taioba crua', slug = 'taioba-crua' WHERE id = 160;
UPDATE foods SET name = 'Tomate cru com semente', slug = 'tomate-cru-com-semente' WHERE id = 161;
UPDATE foods SET name = 'Extrato de tomate', slug = 'extrato-de-tomate' WHERE id = 162;
UPDATE foods SET name = 'Molho de tomate industrializado', slug = 'molho-de-tomate-industrializado' WHERE id = 163;
UPDATE foods SET name = 'Purê de tomate', slug = 'pure-de-tomate' WHERE id = 164;
UPDATE foods SET name = 'Tomate para salada', slug = 'tomate-para-salada' WHERE id = 165;
UPDATE foods SET name = 'Vagem crua', slug = 'vagem-crua' WHERE id = 166;
UPDATE foods SET name = 'Abacate cru', slug = 'abacate-cru' WHERE id = 167;
UPDATE foods SET name = 'Abacaxi cru', slug = 'abacaxi-cru' WHERE id = 168;
UPDATE foods SET name = 'Polpa de abacaxi congelada', slug = 'polpa-de-abacaxi-congelada' WHERE id = 169;
UPDATE foods SET name = 'Abiu cru', slug = 'abiu-cru' WHERE id = 170;
UPDATE foods SET name = 'Açaí com xarope de guaraná e glucose', slug = 'acai-com-xarope-de-guarana-e-glucose' WHERE id = 171;
UPDATE foods SET name = 'Polpa de açaí congelada', slug = 'polpa-de-acai-congelada' WHERE id = 172;
UPDATE foods SET name = 'Acerola crua', slug = 'acerola-crua' WHERE id = 173;
UPDATE foods SET name = 'Polpa de acerola congelada', slug = 'polpa-de-acerola-congelada' WHERE id = 174;
UPDATE foods SET name = 'Ameixa em calda enlatada', slug = 'ameixa-em-calda-enlatada' WHERE id = 175;
UPDATE foods SET name = 'Ameixa crua', slug = 'ameixa-crua' WHERE id = 176;
UPDATE foods SET name = 'Ameixa em calda enlatada drenada', slug = 'ameixa-em-calda-enlatada-drenada' WHERE id = 177;
UPDATE foods SET name = 'Atemoia crua', slug = 'atemoia-crua' WHERE id = 178;
UPDATE foods SET name = 'Banana-da-terra crua', slug = 'banana-da-terra-crua' WHERE id = 179;
UPDATE foods SET name = 'Banana em doce de barra', slug = 'banana-em-doce-de-barra' WHERE id = 180;
UPDATE foods SET name = 'Banana-figo crua', slug = 'banana-figo-crua' WHERE id = 181;
UPDATE foods SET name = 'Banana-maçã crua', slug = 'banana-maca-crua' WHERE id = 182;
UPDATE foods SET name = 'Banana nanica crua', slug = 'banana-nanica-crua' WHERE id = 183;
UPDATE foods SET name = 'Banana-ouro crua', slug = 'banana-ouro-crua' WHERE id = 184;
UPDATE foods SET name = 'Banana-pacova crua', slug = 'banana-pacova-crua' WHERE id = 185;
UPDATE foods SET name = 'Banana-prata crua', slug = 'banana-prata-crua' WHERE id = 186;
UPDATE foods SET name = 'Cacau cru', slug = 'cacau-cru' WHERE id = 187;
UPDATE foods SET name = 'Cajá-manga cru', slug = 'caja-manga-cru' WHERE id = 188;
UPDATE foods SET name = 'Polpa de cajá congelada', slug = 'polpa-de-caja-congelada' WHERE id = 189;
UPDATE foods SET name = 'Caju cru', slug = 'caju-cru' WHERE id = 190;
UPDATE foods SET name = 'Polpa de caju congelada', slug = 'polpa-de-caju-congelada' WHERE id = 191;
UPDATE foods SET name = 'Suco concentrado de caju envasado', slug = 'suco-concentrado-de-caju-envasado' WHERE id = 192;
UPDATE foods SET name = 'Caqui chocolate cru', slug = 'caqui-chocolate-cru' WHERE id = 193;
UPDATE foods SET name = 'Carambola crua', slug = 'carambola-crua' WHERE id = 194;
UPDATE foods SET name = 'Ciriguela crua', slug = 'ciriguela-crua' WHERE id = 195;
UPDATE foods SET name = 'Cupuaçu cru', slug = 'cupuacu-cru' WHERE id = 196;
UPDATE foods SET name = 'Polpa de cupuaçu congelada', slug = 'polpa-de-cupuacu-congelada' WHERE id = 197;
UPDATE foods SET name = 'Figo cru', slug = 'figo-cru' WHERE id = 198;
UPDATE foods SET name = 'Figo enlatado em calda', slug = 'figo-enlatado-em-calda' WHERE id = 199;
UPDATE foods SET name = 'Fruta-pão crua', slug = 'fruta-pao-crua' WHERE id = 200;
UPDATE foods SET name = 'Goiaba branca com casca crua', slug = 'goiaba-branca-com-casca-crua' WHERE id = 201;
UPDATE foods SET name = 'Goiaba em doce de pasta', slug = 'goiaba-em-doce-de-pasta' WHERE id = 202;
UPDATE foods SET name = 'Cascão de goiaba', slug = 'cascao-de-goiaba' WHERE id = 203;
UPDATE foods SET name = 'Goiaba vermelha com casca crua', slug = 'goiaba-vermelha-com-casca-crua' WHERE id = 204;
UPDATE foods SET name = 'Graviola crua', slug = 'graviola-crua' WHERE id = 208;
UPDATE foods SET name = 'Polpa de graviola congelada', slug = 'polpa-de-graviola-congelada' WHERE id = 209;
UPDATE foods SET name = 'Jabuticaba crua', slug = 'jabuticaba-crua' WHERE id = 210;
UPDATE foods SET name = 'Jaca crua', slug = 'jaca-crua' WHERE id = 211;
UPDATE foods SET name = 'Jambo cru', slug = 'jambo-cru' WHERE id = 212;
UPDATE foods SET name = 'Jamelão cru', slug = 'jamelao-cru' WHERE id = 213;
UPDATE foods SET name = 'Kiwi cru', slug = 'kiwi-cru' WHERE id = 214;
UPDATE foods SET name = 'Laranja baía crua', slug = 'laranja-baia-crua' WHERE id = 215;
UPDATE foods SET name = 'Suco de laranja baía', slug = 'suco-de-laranja-baia' WHERE id = 216;
UPDATE foods SET name = 'Laranja-da-terra crua', slug = 'laranja-da-terra-crua' WHERE id = 217;
UPDATE foods SET name = 'Suco de laranja-da-terra', slug = 'suco-de-laranja-da-terra' WHERE id = 218;
UPDATE foods SET name = 'Laranja-lima crua', slug = 'laranja-lima-crua' WHERE id = 219;
UPDATE foods SET name = 'Suco de laranja-lima', slug = 'suco-de-laranja-lima' WHERE id = 220;
UPDATE foods SET name = 'Laranja-pêra crua', slug = 'laranja-pera-crua' WHERE id = 221;
UPDATE foods SET name = 'Suco de laranja-pêra', slug = 'suco-de-laranja-pera' WHERE id = 222;
UPDATE foods SET name = 'Laranja valência crua', slug = 'laranja-valencia-crua' WHERE id = 223;
UPDATE foods SET name = 'Suco de laranja valência', slug = 'suco-de-laranja-valencia' WHERE id = 224;
UPDATE foods SET name = 'Suco de limão cravo', slug = 'suco-de-limao-cravo' WHERE id = 225;
UPDATE foods SET name = 'Suco de limão galego', slug = 'suco-de-limao-galego' WHERE id = 226;
UPDATE foods SET name = 'Limão tahiti cru', slug = 'limao-tahiti-cru' WHERE id = 227;
UPDATE foods SET name = 'Maçã argentina com casca crua', slug = 'maca-argentina-com-casca-crua' WHERE id = 228;
UPDATE foods SET name = 'Maçã fuji com casca crua', slug = 'maca-fuji-com-casca-crua' WHERE id = 229;
UPDATE foods SET name = 'Macaúba crua', slug = 'macauba-crua' WHERE id = 230;
UPDATE foods SET name = 'Mamão em doce de calda drenado', slug = 'mamao-em-doce-de-calda-drenado' WHERE id = 231;
UPDATE foods SET name = 'Mamão formosa cru', slug = 'mamao-formosa-cru' WHERE id = 232;
UPDATE foods SET name = 'Mamão papaia cru', slug = 'mamao-papaia-cru' WHERE id = 233;
UPDATE foods SET name = 'Mamão verde em doce de calda drenado', slug = 'mamao-verde-em-doce-de-calda-drenado' WHERE id = 234;
UPDATE foods SET name = 'Manga haden crua', slug = 'manga-haden-crua' WHERE id = 235;
UPDATE foods SET name = 'Manga palmer crua', slug = 'manga-palmer-crua' WHERE id = 236;
UPDATE foods SET name = 'Polpa de manga congelada', slug = 'polpa-de-manga-congelada' WHERE id = 237;
UPDATE foods SET name = 'Manga tommy atkins crua', slug = 'manga-tommy-atkins-crua' WHERE id = 238;
UPDATE foods SET name = 'Maracujá cru', slug = 'maracuja-cru' WHERE id = 239;
UPDATE foods SET name = 'Polpa de maracujá congelada', slug = 'polpa-de-maracuja-congelada' WHERE id = 240;
UPDATE foods SET name = 'Suco concentrado de maracujá envasado', slug = 'suco-concentrado-de-maracuja-envasado' WHERE id = 241;
UPDATE foods SET name = 'Melancia crua', slug = 'melancia-crua' WHERE id = 242;
UPDATE foods SET name = 'Melão cru', slug = 'melao-cru' WHERE id = 243;
UPDATE foods SET name = 'Mexerica murcote crua', slug = 'mexerica-murcote-crua' WHERE id = 244;
UPDATE foods SET name = 'Mexerica rio crua', slug = 'mexerica-rio-crua' WHERE id = 245;
UPDATE foods SET name = 'Morango cru', slug = 'morango-cru' WHERE id = 246;
UPDATE foods SET name = 'Nêspera crua', slug = 'nespera-crua' WHERE id = 247;
UPDATE foods SET name = 'Pequi cru', slug = 'pequi-cru' WHERE id = 248;
UPDATE foods SET name = 'Pêra park crua', slug = 'pera-park-crua' WHERE id = 249;
UPDATE foods SET name = 'Pêra williams crua', slug = 'pera-williams-crua' WHERE id = 250;
UPDATE foods SET name = 'Pêssego aurora cru', slug = 'pessego-aurora-cru' WHERE id = 251;
UPDATE foods SET name = 'Pêssego enlatado em calda', slug = 'pessego-enlatado-em-calda' WHERE id = 252;
UPDATE foods SET name = 'Pinha crua', slug = 'pinha-crua' WHERE id = 253;
UPDATE foods SET name = 'Pitanga crua', slug = 'pitanga-crua' WHERE id = 254;
UPDATE foods SET name = 'Polpa de pitanga congelada', slug = 'polpa-de-pitanga-congelada' WHERE id = 255;
UPDATE foods SET name = 'Romã crua', slug = 'roma-crua' WHERE id = 256;
UPDATE foods SET name = 'Tamarindo cru', slug = 'tamarindo-cru' WHERE id = 257;
UPDATE foods SET name = 'Tangerina poncã crua', slug = 'tangerina-ponca-crua' WHERE id = 258;
UPDATE foods SET name = 'Suco de tangerina poncã', slug = 'suco-de-tangerina-ponca' WHERE id = 259;
UPDATE foods SET name = 'Tucumã cru', slug = 'tucuma-cru' WHERE id = 260;
UPDATE foods SET name = 'Umbu cru', slug = 'umbu-cru' WHERE id = 261;
UPDATE foods SET name = 'Polpa de umbu congelada', slug = 'polpa-de-umbu-congelada' WHERE id = 262;
UPDATE foods SET name = 'Uva itália crua', slug = 'uva-italia-crua' WHERE id = 263;
UPDATE foods SET name = 'Uva rubi crua', slug = 'uva-rubi-crua' WHERE id = 264;
UPDATE foods SET name = 'Suco concentrado de uva envasado', slug = 'suco-concentrado-de-uva-envasado' WHERE id = 265;
UPDATE foods SET name = 'Azeite de dendê', slug = 'azeite-de-dende' WHERE id = 266;
UPDATE foods SET name = 'Azeite de oliva extra virgem', slug = 'azeite-de-oliva-extra-virgem' WHERE id = 267;
UPDATE foods SET name = 'Manteiga com sal', slug = 'manteiga-com-sal' WHERE id = 268;
UPDATE foods SET name = 'Manteiga sem sal', slug = 'manteiga-sem-sal' WHERE id = 269;
UPDATE foods SET name = 'Margarina com sal 65% lipídeos (óleo hidrogenado)', slug = 'margarina-com-sal-65-lipideos-oleo-hidrogenado' WHERE id = 270;
UPDATE foods SET name = 'Margarina sem sal 80% lipídeos (óleo hidrogenado)', slug = 'margarina-sem-sal-80-lipideos-oleo-hidrogenado' WHERE id = 271;
UPDATE foods SET name = 'Margarina com sal 65% lipídeos (óleo interesterificado)', slug = 'margarina-com-sal-65-lipideos-oleo-interesterificado' WHERE id = 272;
UPDATE foods SET name = 'Margarina sem sal 65% lipídeos (óleo interesterificado)', slug = 'margarina-sem-sal-65-lipideos-oleo-interesterificado' WHERE id = 273;
UPDATE foods SET name = 'Óleo de babaçu', slug = 'oleo-de-babacu' WHERE id = 274;
UPDATE foods SET name = 'Óleo de canola', slug = 'oleo-de-canola' WHERE id = 275;
UPDATE foods SET name = 'Óleo de girassol', slug = 'oleo-de-girassol' WHERE id = 276;
UPDATE foods SET name = 'Óleo de milho', slug = 'oleo-de-milho' WHERE id = 277;
UPDATE foods SET name = 'Óleo de pequi', slug = 'oleo-de-pequi' WHERE id = 278;
UPDATE foods SET name = 'Óleo de soja', slug = 'oleo-de-soja' WHERE id = 279;
UPDATE foods SET name = 'Filé de abadejo congelado assado', slug = 'file-de-abadejo-congelado-assado' WHERE id = 280;
UPDATE foods SET name = 'Filé de abadejo congelado cozido', slug = 'file-de-abadejo-congelado-cozido' WHERE id = 281;
UPDATE foods SET name = 'Filé de abadejo congelado cru', slug = 'file-de-abadejo-congelado-cru' WHERE id = 282;
UPDATE foods SET name = 'Filé de abadejo congelado grelhado', slug = 'file-de-abadejo-congelado-grelhado' WHERE id = 283;
UPDATE foods SET name = 'Atum em conserva no óleo', slug = 'atum-em-conserva-no-oleo' WHERE id = 284;
UPDATE foods SET name = 'Atum fresco cru', slug = 'atum-fresco-cru' WHERE id = 285;
UPDATE foods SET name = 'Bacalhau salgado cru', slug = 'bacalhau-salgado-cru' WHERE id = 286;
UPDATE foods SET name = 'Bacalhau salgado refogado', slug = 'bacalhau-salgado-refogado' WHERE id = 287;
UPDATE foods SET name = 'Posta de cação frita com farinha de trigo', slug = 'posta-de-cacao-frita-com-farinha-de-trigo' WHERE id = 288;
UPDATE foods SET name = 'Posta de cação cozida', slug = 'posta-de-cacao-cozida' WHERE id = 289;
UPDATE foods SET name = 'Posta de cação crua', slug = 'posta-de-cacao-crua' WHERE id = 290;
UPDATE foods SET name = 'Camarão rio grande cozido', slug = 'camarao-rio-grande-cozido' WHERE id = 291;
UPDATE foods SET name = 'Camarão rio grande cru', slug = 'camarao-rio-grande-cru' WHERE id = 292;
UPDATE foods SET name = 'Camarão sete barbas frito sem cabeça com casca', slug = 'camarao-sete-barbas-frito-sem-cabeca-com-casca' WHERE id = 293;
UPDATE foods SET name = 'Caranguejo cozido', slug = 'caranguejo-cozido' WHERE id = 294;
UPDATE foods SET name = 'Corimba cru', slug = 'corimba-cru' WHERE id = 295;
UPDATE foods SET name = 'Corimbatá assado', slug = 'corimbata-assado' WHERE id = 296;
UPDATE foods SET name = 'Corimbatá cozido', slug = 'corimbata-cozido' WHERE id = 297;
UPDATE foods SET name = 'Corvina de água doce crua', slug = 'corvina-de-agua-doce-crua' WHERE id = 298;
UPDATE foods SET name = 'Corvina do mar crua', slug = 'corvina-do-mar-crua' WHERE id = 299;
UPDATE foods SET name = 'Corvina grande assada', slug = 'corvina-grande-assada' WHERE id = 300;
UPDATE foods SET name = 'Corvina grande cozida', slug = 'corvina-grande-cozida' WHERE id = 301;
UPDATE foods SET name = 'Dourado de água doce fresco', slug = 'dourado-de-agua-doce-fresco' WHERE id = 302;
UPDATE foods SET name = 'Lambari congelado cru', slug = 'lambari-congelado-cru' WHERE id = 303;
UPDATE foods SET name = 'Lambari congelado frito', slug = 'lambari-congelado-frito' WHERE id = 304;
UPDATE foods SET name = 'Lambari fresco cru', slug = 'lambari-fresco-cru' WHERE id = 305;
UPDATE foods SET name = 'Manjuba frita com farinha de trigo', slug = 'manjuba-frita-com-farinha-de-trigo' WHERE id = 306;
UPDATE foods SET name = 'Manjuba frita', slug = 'manjuba-frita' WHERE id = 307;
UPDATE foods SET name = 'Filé de merluza assado', slug = 'file-de-merluza-assado' WHERE id = 308;
UPDATE foods SET name = 'Filé de merluza cru', slug = 'file-de-merluza-cru' WHERE id = 309;
UPDATE foods SET name = 'Filé de merluza frito', slug = 'file-de-merluza-frito' WHERE id = 310;
UPDATE foods SET name = 'Pescada branca crua', slug = 'pescada-branca-crua' WHERE id = 311;
UPDATE foods SET name = 'Pescada branca frita', slug = 'pescada-branca-frita' WHERE id = 312;
UPDATE foods SET name = 'Filé de pescada frito com farinha de trigo', slug = 'file-de-pescada-frito-com-farinha-de-trigo' WHERE id = 313;
UPDATE foods SET name = 'Filé de pescada cru', slug = 'file-de-pescada-cru' WHERE id = 314;
UPDATE foods SET name = 'Filé de pescada frito', slug = 'file-de-pescada-frito' WHERE id = 315;
UPDATE foods SET name = 'Filé de pescada ao escabeche', slug = 'file-de-pescada-ao-escabeche' WHERE id = 316;
UPDATE foods SET name = 'Pescadinha crua', slug = 'pescadinha-crua' WHERE id = 317;
UPDATE foods SET name = 'Pintado assado', slug = 'pintado-assado' WHERE id = 318;
UPDATE foods SET name = 'Pintado cru', slug = 'pintado-cru' WHERE id = 319;
UPDATE foods SET name = 'Pintado grelhado', slug = 'pintado-grelhado' WHERE id = 320;
UPDATE foods SET name = 'Porquinho cru', slug = 'porquinho-cru' WHERE id = 321;
UPDATE foods SET name = 'Filé de salmão grelhado com pele', slug = 'file-de-salmao-grelhado-com-pele' WHERE id = 322;
UPDATE foods SET name = 'Salmão fresco cru sem pele', slug = 'salmao-fresco-cru-sem-pele' WHERE id = 323;
UPDATE foods SET name = 'Salmão fresco grelhado sem pele', slug = 'salmao-fresco-grelhado-sem-pele' WHERE id = 324;
UPDATE foods SET name = 'Sardinha assada', slug = 'sardinha-assada' WHERE id = 325;
UPDATE foods SET name = 'Sardinha em conserva no óleo', slug = 'sardinha-em-conserva-no-oleo' WHERE id = 326;
UPDATE foods SET name = 'Sardinha frita', slug = 'sardinha-frita' WHERE id = 327;
UPDATE foods SET name = 'Sardinha inteira crua', slug = 'sardinha-inteira-crua' WHERE id = 328;
UPDATE foods SET name = 'Filé de tucunaré congelado cru', slug = 'file-de-tucunare-congelado-cru' WHERE id = 329;
UPDATE foods SET name = 'Apresuntado', slug = 'apresuntado' WHERE id = 330;
UPDATE foods SET name = 'Caldo de carne em tablete', slug = 'caldo-de-carne-em-tablete' WHERE id = 331;
UPDATE foods SET name = 'Caldo de galinha em tablete', slug = 'caldo-de-galinha-em-tablete' WHERE id = 332;
UPDATE foods SET name = 'Acém bovino moído cozido', slug = 'acem-bovino-moido-cozido' WHERE id = 333;
UPDATE foods SET name = 'Acém bovino moído cru', slug = 'acem-bovino-moido-cru' WHERE id = 334;
UPDATE foods SET name = 'Acém bovino sem gordura cozido', slug = 'acem-bovino-sem-gordura-cozido' WHERE id = 335;
UPDATE foods SET name = 'Acém bovino sem gordura cru', slug = 'acem-bovino-sem-gordura-cru' WHERE id = 336;
UPDATE foods SET name = 'Almôndegas bovinas cruas', slug = 'almondegas-bovinas-cruas' WHERE id = 337;
UPDATE foods SET name = 'Almôndegas bovinas fritas', slug = 'almondegas-bovinas-fritas' WHERE id = 338;
UPDATE foods SET name = 'Bucho bovino cozido', slug = 'bucho-bovino-cozido' WHERE id = 339;
UPDATE foods SET name = 'Bucho bovino cru', slug = 'bucho-bovino-cru' WHERE id = 340;
UPDATE foods SET name = 'Capa de contra-filé com gordura crua', slug = 'capa-de-contra-file-com-gordura-crua' WHERE id = 341;
UPDATE foods SET name = 'Capa de contra-filé com gordura grelhada', slug = 'capa-de-contra-file-com-gordura-grelhada' WHERE id = 342;
UPDATE foods SET name = 'Capa de contra-filé sem gordura crua', slug = 'capa-de-contra-file-sem-gordura-crua' WHERE id = 343;
UPDATE foods SET name = 'Capa de contra-filé sem gordura grelhada', slug = 'capa-de-contra-file-sem-gordura-grelhada' WHERE id = 344;
UPDATE foods SET name = 'Charque bovino cozido', slug = 'charque-bovino-cozido' WHERE id = 345;
UPDATE foods SET name = 'Charque bovino cru', slug = 'charque-bovino-cru' WHERE id = 346;
UPDATE foods SET name = 'Contra-filé bovino à milanesa', slug = 'contra-file-bovino-a-milanesa' WHERE id = 347;
UPDATE foods SET name = 'Contra-filé de costela bovino cru', slug = 'contra-file-de-costela-bovino-cru' WHERE id = 348;
UPDATE foods SET name = 'Contra-filé de costela bovino grelhado', slug = 'contra-file-de-costela-bovino-grelhado' WHERE id = 349;
UPDATE foods SET name = 'Contra-filé bovino com gordura cru', slug = 'contra-file-bovino-com-gordura-cru' WHERE id = 350;
UPDATE foods SET name = 'Contra-filé bovino com gordura grelhado', slug = 'contra-file-bovino-com-gordura-grelhado' WHERE id = 351;
UPDATE foods SET name = 'Contra-filé bovino sem gordura cru', slug = 'contra-file-bovino-sem-gordura-cru' WHERE id = 352;
UPDATE foods SET name = 'Contra-filé bovino sem gordura grelhado', slug = 'contra-file-bovino-sem-gordura-grelhado' WHERE id = 353;
UPDATE foods SET name = 'Costela bovina assada', slug = 'costela-bovina-assada' WHERE id = 354;
UPDATE foods SET name = 'Costela bovina crua', slug = 'costela-bovina-crua' WHERE id = 355;
UPDATE foods SET name = 'Coxão duro bovino sem gordura cozido', slug = 'coxao-duro-bovino-sem-gordura-cozido' WHERE id = 356;
UPDATE foods SET name = 'Coxão duro bovino sem gordura cru', slug = 'coxao-duro-bovino-sem-gordura-cru' WHERE id = 357;
UPDATE foods SET name = 'Coxão mole bovino sem gordura cozido', slug = 'coxao-mole-bovino-sem-gordura-cozido' WHERE id = 358;
UPDATE foods SET name = 'Coxão mole bovino sem gordura cru', slug = 'coxao-mole-bovino-sem-gordura-cru' WHERE id = 359;
UPDATE foods SET name = 'Cupim bovino assado', slug = 'cupim-bovino-assado' WHERE id = 360;
UPDATE foods SET name = 'Cupim bovino cru', slug = 'cupim-bovino-cru' WHERE id = 361;
UPDATE foods SET name = 'Fígado bovino cru', slug = 'figado-bovino-cru' WHERE id = 362;
UPDATE foods SET name = 'Fígado bovino grelhado', slug = 'figado-bovino-grelhado' WHERE id = 363;
UPDATE foods SET name = 'Filé mignon bovino sem gordura cru', slug = 'file-mignon-bovino-sem-gordura-cru' WHERE id = 364;
UPDATE foods SET name = 'Filé mignon bovino sem gordura grelhado', slug = 'file-mignon-bovino-sem-gordura-grelhado' WHERE id = 365;
UPDATE foods SET name = 'Flanco bovino sem gordura cozido', slug = 'flanco-bovino-sem-gordura-cozido' WHERE id = 366;
UPDATE foods SET name = 'Flanco bovino sem gordura cru', slug = 'flanco-bovino-sem-gordura-cru' WHERE id = 367;
UPDATE foods SET name = 'Fraldinha bovina com gordura cozida', slug = 'fraldinha-bovina-com-gordura-cozida' WHERE id = 368;
UPDATE foods SET name = 'Fraldinha bovina com gordura crua', slug = 'fraldinha-bovina-com-gordura-crua' WHERE id = 369;
UPDATE foods SET name = 'Lagarto bovino cozido', slug = 'lagarto-bovino-cozido' WHERE id = 370;
UPDATE foods SET name = 'Lagarto bovino cru', slug = 'lagarto-bovino-cru' WHERE id = 371;
UPDATE foods SET name = 'Língua bovina cozida', slug = 'lingua-bovina-cozida' WHERE id = 372;
UPDATE foods SET name = 'Língua bovina crua', slug = 'lingua-bovina-crua' WHERE id = 373;
UPDATE foods SET name = 'Maminha bovina crua', slug = 'maminha-bovina-crua' WHERE id = 374;
UPDATE foods SET name = 'Maminha bovina grelhada', slug = 'maminha-bovina-grelhada' WHERE id = 375;
UPDATE foods SET name = 'Miolo de alcatra bovino sem gordura cru', slug = 'miolo-de-alcatra-bovino-sem-gordura-cru' WHERE id = 376;
UPDATE foods SET name = 'Miolo de alcatra bovino sem gordura grelhado', slug = 'miolo-de-alcatra-bovino-sem-gordura-grelhado' WHERE id = 377;
UPDATE foods SET name = 'Músculo bovino sem gordura cozido', slug = 'musculo-bovino-sem-gordura-cozido' WHERE id = 378;
UPDATE foods SET name = 'Músculo bovino sem gordura cru', slug = 'musculo-bovino-sem-gordura-cru' WHERE id = 379;
UPDATE foods SET name = 'Paleta bovina com gordura crua', slug = 'paleta-bovina-com-gordura-crua' WHERE id = 380;
UPDATE foods SET name = 'Paleta bovina sem gordura cozida', slug = 'paleta-bovina-sem-gordura-cozida' WHERE id = 381;
UPDATE foods SET name = 'Paleta bovina sem gordura crua', slug = 'paleta-bovina-sem-gordura-crua' WHERE id = 382;
UPDATE foods SET name = 'Patinho bovino sem gordura cru', slug = 'patinho-bovino-sem-gordura-cru' WHERE id = 383;
UPDATE foods SET name = 'Patinho bovino sem gordura grelhado', slug = 'patinho-bovino-sem-gordura-grelhado' WHERE id = 384;
UPDATE foods SET name = 'Peito bovino sem gordura cozido', slug = 'peito-bovino-sem-gordura-cozido' WHERE id = 385;
UPDATE foods SET name = 'Peito bovino sem gordura cru', slug = 'peito-bovino-sem-gordura-cru' WHERE id = 386;
UPDATE foods SET name = 'Picanha bovina com gordura crua', slug = 'picanha-bovina-com-gordura-crua' WHERE id = 387;
UPDATE foods SET name = 'Picanha bovina com gordura grelhada', slug = 'picanha-bovina-com-gordura-grelhada' WHERE id = 388;
UPDATE foods SET name = 'Picanha bovina sem gordura crua', slug = 'picanha-bovina-sem-gordura-crua' WHERE id = 389;
UPDATE foods SET name = 'Picanha bovina sem gordura grelhada', slug = 'picanha-bovina-sem-gordura-grelhada' WHERE id = 390;
UPDATE foods SET name = 'Carne seca bovina cozida', slug = 'carne-seca-bovina-cozida' WHERE id = 391;
UPDATE foods SET name = 'Carne seca bovina crua', slug = 'carne-seca-bovina-crua' WHERE id = 392;
UPDATE foods SET name = 'Coxinha de frango frita', slug = 'coxinha-de-frango-frita' WHERE id = 393;
UPDATE foods SET name = 'Croquete de carne cru', slug = 'croquete-de-carne-cru' WHERE id = 394;
UPDATE foods SET name = 'Croquete de carne frito', slug = 'croquete-de-carne-frito' WHERE id = 395;
UPDATE foods SET name = 'Empada de frango assada', slug = 'empada-de-frango-assada' WHERE id = 396;
UPDATE foods SET name = 'Empada de frango pré-cozida', slug = 'empada-de-frango-pre-cozida' WHERE id = 397;
UPDATE foods SET name = 'Asa de frango com pele crua', slug = 'asa-de-frango-com-pele-crua' WHERE id = 398;
UPDATE foods SET name = 'Frango caipira inteiro com pele cozido', slug = 'frango-caipira-inteiro-com-pele-cozido' WHERE id = 399;
UPDATE foods SET name = 'Frango caipira inteiro sem pele cozido', slug = 'frango-caipira-inteiro-sem-pele-cozido' WHERE id = 400;
UPDATE foods SET name = 'Coração de frango cru', slug = 'coracao-de-frango-cru' WHERE id = 401;
UPDATE foods SET name = 'Coração de frango grelhado', slug = 'coracao-de-frango-grelhado' WHERE id = 402;
UPDATE foods SET name = 'Coxa de frango com pele assada', slug = 'coxa-de-frango-com-pele-assada' WHERE id = 403;
UPDATE foods SET name = 'Coxa de frango com pele crua', slug = 'coxa-de-frango-com-pele-crua' WHERE id = 404;
UPDATE foods SET name = 'Coxa de frango sem pele cozida', slug = 'coxa-de-frango-sem-pele-cozida' WHERE id = 405;
UPDATE foods SET name = 'Coxa de frango sem pele crua', slug = 'coxa-de-frango-sem-pele-crua' WHERE id = 406;
UPDATE foods SET name = 'Fígado de frango cru', slug = 'figado-de-frango-cru' WHERE id = 407;
UPDATE foods SET name = 'Filé de frango à milanesa', slug = 'file-de-frango-a-milanesa' WHERE id = 408;
UPDATE foods SET name = 'Frango inteiro com pele cru', slug = 'frango-inteiro-com-pele-cru' WHERE id = 409;
UPDATE foods SET name = 'Frango inteiro sem pele assado', slug = 'frango-inteiro-sem-pele-assado' WHERE id = 410;
UPDATE foods SET name = 'Frango inteiro sem pele cozido', slug = 'frango-inteiro-sem-pele-cozido' WHERE id = 411;
UPDATE foods SET name = 'Frango inteiro sem pele cru', slug = 'frango-inteiro-sem-pele-cru' WHERE id = 412;
UPDATE foods SET name = 'Peito de frango com pele assado', slug = 'peito-de-frango-com-pele-assado' WHERE id = 413;
UPDATE foods SET name = 'Peito de frango com pele cru', slug = 'peito-de-frango-com-pele-cru' WHERE id = 414;
UPDATE foods SET name = 'Peito de frango sem pele cozido', slug = 'peito-de-frango-sem-pele-cozido' WHERE id = 415;
UPDATE foods SET name = 'Peito de frango sem pele cru', slug = 'peito-de-frango-sem-pele-cru' WHERE id = 416;
UPDATE foods SET name = 'Peito de frango sem pele grelhado', slug = 'peito-de-frango-sem-pele-grelhado' WHERE id = 417;
UPDATE foods SET name = 'Sobrecoxa de frango com pele assada', slug = 'sobrecoxa-de-frango-com-pele-assada' WHERE id = 418;
UPDATE foods SET name = 'Sobrecoxa de frango com pele crua', slug = 'sobrecoxa-de-frango-com-pele-crua' WHERE id = 419;
UPDATE foods SET name = 'Sobrecoxa de frango sem pele assada', slug = 'sobrecoxa-de-frango-sem-pele-assada' WHERE id = 420;
UPDATE foods SET name = 'Sobrecoxa de frango sem pele crua', slug = 'sobrecoxa-de-frango-sem-pele-crua' WHERE id = 421;
UPDATE foods SET name = 'Hambúrguer bovino cru', slug = 'hamburguer-bovino-cru' WHERE id = 422;
UPDATE foods SET name = 'Hambúrguer bovino frito', slug = 'hamburguer-bovino-frito' WHERE id = 423;
UPDATE foods SET name = 'Hambúrguer bovino grelhado', slug = 'hamburguer-bovino-grelhado' WHERE id = 424;
UPDATE foods SET name = 'Linguiça de frango crua', slug = 'linguica-de-frango-crua' WHERE id = 425;
UPDATE foods SET name = 'Linguiça de frango frita', slug = 'linguica-de-frango-frita' WHERE id = 426;
UPDATE foods SET name = 'Linguiça de frango grelhada', slug = 'linguica-de-frango-grelhada' WHERE id = 427;
UPDATE foods SET name = 'Linguiça de porco crua', slug = 'linguica-de-porco-crua' WHERE id = 428;
UPDATE foods SET name = 'Linguiça de porco frita', slug = 'linguica-de-porco-frita' WHERE id = 429;
UPDATE foods SET name = 'Linguiça de porco grelhada', slug = 'linguica-de-porco-grelhada' WHERE id = 430;
UPDATE foods SET name = 'Mortadela', slug = 'mortadela' WHERE id = 431;
UPDATE foods SET name = 'Peru congelado assado', slug = 'peru-congelado-assado' WHERE id = 432;
UPDATE foods SET name = 'Peru congelado cru', slug = 'peru-congelado-cru' WHERE id = 433;
UPDATE foods SET name = 'Bisteca de porco crua', slug = 'bisteca-de-porco-crua' WHERE id = 434;
UPDATE foods SET name = 'Bisteca de porco frita', slug = 'bisteca-de-porco-frita' WHERE id = 435;
UPDATE foods SET name = 'Bisteca de porco grelhada', slug = 'bisteca-de-porco-grelhada' WHERE id = 436;
UPDATE foods SET name = 'Costela de porco assada', slug = 'costela-de-porco-assada' WHERE id = 437;
UPDATE foods SET name = 'Costela de porco crua', slug = 'costela-de-porco-crua' WHERE id = 438;
UPDATE foods SET name = 'Lombo de porco assado', slug = 'lombo-de-porco-assado' WHERE id = 439;
UPDATE foods SET name = 'Lombo de porco cru', slug = 'lombo-de-porco-cru' WHERE id = 440;
UPDATE foods SET name = 'Orelha de porco salgada crua', slug = 'orelha-de-porco-salgada-crua' WHERE id = 441;
UPDATE foods SET name = 'Pernil de porco assado', slug = 'pernil-de-porco-assado' WHERE id = 442;
UPDATE foods SET name = 'Pernil de porco cru', slug = 'pernil-de-porco-cru' WHERE id = 443;
UPDATE foods SET name = 'Rabo de porco salgado cru', slug = 'rabo-de-porco-salgado-cru' WHERE id = 444;
UPDATE foods SET name = 'Presunto com capa de gordura', slug = 'presunto-com-capa-de-gordura' WHERE id = 445;
UPDATE foods SET name = 'Presunto sem capa de gordura', slug = 'presunto-sem-capa-de-gordura' WHERE id = 446;
UPDATE foods SET name = 'Quibe assado', slug = 'quibe-assado' WHERE id = 447;
UPDATE foods SET name = 'Quibe cru', slug = 'quibe-cru' WHERE id = 448;
UPDATE foods SET name = 'Quibe frito', slug = 'quibe-frito' WHERE id = 449;
UPDATE foods SET name = 'Salame', slug = 'salame' WHERE id = 450;
UPDATE foods SET name = 'Toucinho cru', slug = 'toucinho-cru' WHERE id = 451;
UPDATE foods SET name = 'Toucinho frito', slug = 'toucinho-frito' WHERE id = 452;
UPDATE foods SET name = 'Bebida láctea de pêssego', slug = 'bebida-lactea-de-pessego' WHERE id = 453;
UPDATE foods SET name = 'Creme de leite', slug = 'creme-de-leite' WHERE id = 454;
UPDATE foods SET name = 'Iogurte natural', slug = 'iogurte-natural' WHERE id = 455;
UPDATE foods SET name = 'Iogurte natural desnatado', slug = 'iogurte-natural-desnatado' WHERE id = 456;
UPDATE foods SET name = 'Iogurte sabor morango', slug = 'iogurte-sabor-morango' WHERE id = 457;
UPDATE foods SET name = 'Iogurte sabor pêssego', slug = 'iogurte-sabor-pessego' WHERE id = 458;
UPDATE foods SET name = 'Leite condensado', slug = 'leite-condensado' WHERE id = 459;
UPDATE foods SET name = 'Leite de cabra', slug = 'leite-de-cabra' WHERE id = 460;
UPDATE foods SET name = 'Leite achocolatado', slug = 'leite-achocolatado' WHERE id = 461;
UPDATE foods SET name = 'Leite de vaca desnatado em pó', slug = 'leite-de-vaca-desnatado-em-po' WHERE id = 462;
UPDATE foods SET name = 'Leite de vaca integral em pó', slug = 'leite-de-vaca-integral-em-po' WHERE id = 463;
UPDATE foods SET name = 'Leite fermentado', slug = 'leite-fermentado' WHERE id = 464;
UPDATE foods SET name = 'Queijo minas frescal', slug = 'queijo-minas-frescal' WHERE id = 465;
UPDATE foods SET name = 'Queijo minas meia cura', slug = 'queijo-minas-meia-cura' WHERE id = 466;
UPDATE foods SET name = 'Queijo mozarela', slug = 'queijo-mozarela' WHERE id = 467;
UPDATE foods SET name = 'Queijo parmesão', slug = 'queijo-parmesao' WHERE id = 468;
UPDATE foods SET name = 'Queijo pasteurizado', slug = 'queijo-pasteurizado' WHERE id = 469;
UPDATE foods SET name = 'Queijo petit suisse de morango', slug = 'queijo-petit-suisse-de-morango' WHERE id = 470;
UPDATE foods SET name = 'Queijo prato', slug = 'queijo-prato' WHERE id = 471;
UPDATE foods SET name = 'Requeijão cremoso', slug = 'requeijao-cremoso' WHERE id = 472;
UPDATE foods SET name = 'Ricota', slug = 'ricota' WHERE id = 473;
UPDATE foods SET name = 'Bebida isotônica', slug = 'bebida-isotonica' WHERE id = 474;
UPDATE foods SET name = 'Café infusão 10%', slug = 'cafe-infusao-10' WHERE id = 475;
UPDATE foods SET name = 'Aguardente de cana', slug = 'aguardente-de-cana' WHERE id = 476;
UPDATE foods SET name = 'Caldo de cana', slug = 'caldo-de-cana' WHERE id = 477;
UPDATE foods SET name = 'Cerveja pilsen', slug = 'cerveja-pilsen' WHERE id = 478;
UPDATE foods SET name = 'Chá de erva-doce', slug = 'cha-de-erva-doce' WHERE id = 479;
UPDATE foods SET name = 'Chá mate', slug = 'cha-mate' WHERE id = 480;
UPDATE foods SET name = 'Chá preto', slug = 'cha-preto' WHERE id = 481;
UPDATE foods SET name = 'Água de coco', slug = 'agua-de-coco' WHERE id = 482;
UPDATE foods SET name = 'Refrigerante água tônica', slug = 'refrigerante-agua-tonica' WHERE id = 483;
UPDATE foods SET name = 'Refrigerante tipo cola', slug = 'refrigerante-tipo-cola' WHERE id = 484;
UPDATE foods SET name = 'Refrigerante guaraná', slug = 'refrigerante-guarana' WHERE id = 485;
UPDATE foods SET name = 'Refrigerante laranja', slug = 'refrigerante-laranja' WHERE id = 486;
UPDATE foods SET name = 'Refrigerante limão', slug = 'refrigerante-limao' WHERE id = 487;
UPDATE foods SET name = 'Omelete de queijo', slug = 'omelete-de-queijo' WHERE id = 488;
UPDATE foods SET name = 'Ovo de codorna inteiro cru', slug = 'ovo-de-codorna-inteiro-cru' WHERE id = 489;
UPDATE foods SET name = 'Clara de ovo de galinha cozida', slug = 'clara-de-ovo-de-galinha-cozida' WHERE id = 490;
UPDATE foods SET name = 'Gema de ovo de galinha cozida', slug = 'gema-de-ovo-de-galinha-cozida' WHERE id = 491;
UPDATE foods SET name = 'Ovo de galinha inteiro cozido', slug = 'ovo-de-galinha-inteiro-cozido' WHERE id = 492;
UPDATE foods SET name = 'Ovo de galinha inteiro cru', slug = 'ovo-de-galinha-inteiro-cru' WHERE id = 493;
UPDATE foods SET name = 'Ovo de galinha frito', slug = 'ovo-de-galinha-frito' WHERE id = 494;
UPDATE foods SET name = 'Achocolatado em pó', slug = 'achocolatado-em-po' WHERE id = 495;
UPDATE foods SET name = 'Açúcar cristal', slug = 'acucar-cristal' WHERE id = 496;
UPDATE foods SET name = 'Açúcar mascavo', slug = 'acucar-mascavo' WHERE id = 497;
UPDATE foods SET name = 'Açúcar refinado', slug = 'acucar-refinado' WHERE id = 498;
UPDATE foods SET name = 'Chocolate ao leite', slug = 'chocolate-ao-leite' WHERE id = 499;
UPDATE foods SET name = 'Chocolate ao leite com castanha do pará', slug = 'chocolate-ao-leite-com-castanha-do-para' WHERE id = 500;
UPDATE foods SET name = 'Chocolate ao leite dietético', slug = 'chocolate-ao-leite-dietetico' WHERE id = 501;
UPDATE foods SET name = 'Chocolate meio amargo', slug = 'chocolate-meio-amargo' WHERE id = 502;
UPDATE foods SET name = 'Cocada branca', slug = 'cocada-branca' WHERE id = 503;
UPDATE foods SET name = 'Doce de abóbora cremoso', slug = 'doce-de-abobora-cremoso' WHERE id = 504;
UPDATE foods SET name = 'Doce de leite cremoso', slug = 'doce-de-leite-cremoso' WHERE id = 505;
UPDATE foods SET name = 'Geleia de mocotó natural', slug = 'geleia-de-mocoto-natural' WHERE id = 506;
UPDATE foods SET name = 'Glicose de milho', slug = 'glicose-de-milho' WHERE id = 507;
UPDATE foods SET name = 'Maria mole', slug = 'maria-mole' WHERE id = 508;
UPDATE foods SET name = 'Maria mole de coco queimado', slug = 'maria-mole-de-coco-queimado' WHERE id = 509;
UPDATE foods SET name = 'Marmelada', slug = 'marmelada' WHERE id = 510;
UPDATE foods SET name = 'Mel de abelha', slug = 'mel-de-abelha' WHERE id = 511;
UPDATE foods SET name = 'Melado', slug = 'melado' WHERE id = 512;
UPDATE foods SET name = 'Quindim', slug = 'quindim' WHERE id = 513;
UPDATE foods SET name = 'Rapadura', slug = 'rapadura' WHERE id = 514;
UPDATE foods SET name = 'Café em pó torrado', slug = 'cafe-em-po-torrado' WHERE id = 515;
UPDATE foods SET name = 'Cappuccino em pó', slug = 'cappuccino-em-po' WHERE id = 516;
UPDATE foods SET name = 'Fermento em pó químico', slug = 'fermento-em-po-quimico' WHERE id = 517;
UPDATE foods SET name = 'Fermento biológico em tablete', slug = 'fermento-biologico-em-tablete' WHERE id = 518;
UPDATE foods SET name = 'Gelatina em pó sabores variados', slug = 'gelatina-em-po-sabores-variados' WHERE id = 519;
UPDATE foods SET name = 'Shoyu', slug = 'shoyu' WHERE id = 520;
UPDATE foods SET name = 'Tempero à base de sal', slug = 'tempero-a-base-de-sal' WHERE id = 521;
UPDATE foods SET name = 'Azeitona preta em conserva', slug = 'azeitona-preta-em-conserva' WHERE id = 522;
UPDATE foods SET name = 'Azeitona verde em conserva', slug = 'azeitona-verde-em-conserva' WHERE id = 523;
UPDATE foods SET name = 'Chantilly em spray com gordura vegetal', slug = 'chantilly-em-spray-com-gordura-vegetal' WHERE id = 524;
UPDATE foods SET name = 'Leite de coco', slug = 'leite-de-coco' WHERE id = 525;
UPDATE foods SET name = 'Maionese tradicional com ovos', slug = 'maionese-tradicional-com-ovos' WHERE id = 526;
UPDATE foods SET name = 'Acarajé', slug = 'acaraje' WHERE id = 527;
UPDATE foods SET name = 'Arroz carreteiro', slug = 'arroz-carreteiro' WHERE id = 528;
UPDATE foods SET name = 'Baião de dois', slug = 'baiao-de-dois' WHERE id = 529;
UPDATE foods SET name = 'Barreado', slug = 'barreado' WHERE id = 530;
UPDATE foods SET name = 'Bife à cavalo com contra-filé', slug = 'bife-a-cavalo-com-contra-file' WHERE id = 531;
UPDATE foods SET name = 'Bolinho de arroz', slug = 'bolinho-de-arroz' WHERE id = 532;
UPDATE foods SET name = 'Camarão à baiana', slug = 'camarao-a-baiana' WHERE id = 533;
UPDATE foods SET name = 'Charuto de repolho', slug = 'charuto-de-repolho' WHERE id = 534;
UPDATE foods SET name = 'Cuscuz de milho cozido com sal', slug = 'cuscuz-de-milho-cozido-com-sal' WHERE id = 535;
UPDATE foods SET name = 'Cuscuz paulista', slug = 'cuscuz-paulista' WHERE id = 536;
UPDATE foods SET name = 'Molho cuxá', slug = 'molho-cuxa' WHERE id = 537;
UPDATE foods SET name = 'Dobradinha', slug = 'dobradinha' WHERE id = 538;
UPDATE foods SET name = 'Estrogonofe de carne', slug = 'estrogonofe-de-carne' WHERE id = 539;
UPDATE foods SET name = 'Estrogonofe de frango', slug = 'estrogonofe-de-frango' WHERE id = 540;
UPDATE foods SET name = 'Feijão tropeiro mineiro', slug = 'feijao-tropeiro-mineiro' WHERE id = 541;
UPDATE foods SET name = 'Frango com açafrão', slug = 'frango-com-acafrao' WHERE id = 543;
UPDATE foods SET name = 'Macarrão ao molho bolognesa', slug = 'macarrao-ao-molho-bolognesa' WHERE id = 544;
UPDATE foods SET name = 'Maniçoba', slug = 'manicoba' WHERE id = 545;
UPDATE foods SET name = 'Quibebe', slug = 'quibebe' WHERE id = 546;
UPDATE foods SET name = 'Salada de legumes com maionese', slug = 'salada-de-legumes-com-maionese' WHERE id = 547;
UPDATE foods SET name = 'Salada de legumes cozida no vapor', slug = 'salada-de-legumes-cozida-no-vapor' WHERE id = 548;
UPDATE foods SET name = 'Salpicão de frango', slug = 'salpicao-de-frango' WHERE id = 549;
UPDATE foods SET name = 'Sarapatel', slug = 'sarapatel' WHERE id = 550;
UPDATE foods SET name = 'Tabule', slug = 'tabule' WHERE id = 551;
UPDATE foods SET name = 'Tacacá', slug = 'tacaca' WHERE id = 552;
UPDATE foods SET name = 'Tapioca com manteiga', slug = 'tapioca-com-manteiga' WHERE id = 553;
UPDATE foods SET name = 'Tucupi com pimenta-de-cheiro', slug = 'tucupi-com-pimenta-de-cheiro' WHERE id = 554;
UPDATE foods SET name = 'Vaca atolada', slug = 'vaca-atolada' WHERE id = 555;
UPDATE foods SET name = 'Vatapá', slug = 'vatapa' WHERE id = 556;
UPDATE foods SET name = 'Virado à paulista', slug = 'virado-a-paulista' WHERE id = 557;
UPDATE foods SET name = 'Yakisoba', slug = 'yakisoba' WHERE id = 558;
UPDATE foods SET name = 'Amendoim em grão cru', slug = 'amendoim-em-grao-cru' WHERE id = 559;
UPDATE foods SET name = 'Amendoim torrado salgado', slug = 'amendoim-torrado-salgado' WHERE id = 560;
UPDATE foods SET name = 'Ervilha em vagem', slug = 'ervilha-em-vagem' WHERE id = 561;
UPDATE foods SET name = 'Ervilha enlatada drenada', slug = 'ervilha-enlatada-drenada' WHERE id = 562;
UPDATE foods SET name = 'Feijão carioca cozido', slug = 'feijao-carioca-cozido' WHERE id = 563;
UPDATE foods SET name = 'Feijão carioca cru', slug = 'feijao-carioca-cru' WHERE id = 564;
UPDATE foods SET name = 'Feijão fradinho cozido', slug = 'feijao-fradinho-cozido' WHERE id = 565;
UPDATE foods SET name = 'Feijão fradinho cru', slug = 'feijao-fradinho-cru' WHERE id = 566;
UPDATE foods SET name = 'Feijão jalo cozido', slug = 'feijao-jalo-cozido' WHERE id = 567;
UPDATE foods SET name = 'Feijão jalo cru', slug = 'feijao-jalo-cru' WHERE id = 568;
UPDATE foods SET name = 'Feijão preto cozido', slug = 'feijao-preto-cozido' WHERE id = 569;
UPDATE foods SET name = 'Feijão preto cru', slug = 'feijao-preto-cru' WHERE id = 570;
UPDATE foods SET name = 'Feijão rajado cozido', slug = 'feijao-rajado-cozido' WHERE id = 571;
UPDATE foods SET name = 'Feijão rajado cru', slug = 'feijao-rajado-cru' WHERE id = 572;
UPDATE foods SET name = 'Feijão rosinha cozido', slug = 'feijao-rosinha-cozido' WHERE id = 573;
UPDATE foods SET name = 'Feijão rosinha cru', slug = 'feijao-rosinha-cru' WHERE id = 574;
UPDATE foods SET name = 'Feijão roxo cozido', slug = 'feijao-roxo-cozido' WHERE id = 575;
UPDATE foods SET name = 'Feijão roxo cru', slug = 'feijao-roxo-cru' WHERE id = 576;
UPDATE foods SET name = 'Grão-de-bico cru', slug = 'grao-de-bico-cru' WHERE id = 577;
UPDATE foods SET name = 'Guandu cru', slug = 'guandu-cru' WHERE id = 578;
UPDATE foods SET name = 'Lentilha cozida', slug = 'lentilha-cozida' WHERE id = 579;
UPDATE foods SET name = 'Lentilha crua', slug = 'lentilha-crua' WHERE id = 580;
UPDATE foods SET name = 'Paçoca de amendoim', slug = 'pacoca-de-amendoim' WHERE id = 581;
UPDATE foods SET name = 'Pé-de-moleque de amendoim', slug = 'pe-de-moleque-de-amendoim' WHERE id = 582;
UPDATE foods SET name = 'Farinha de soja', slug = 'farinha-de-soja' WHERE id = 583;
UPDATE foods SET name = 'Extrato de soja natural fluido', slug = 'extrato-de-soja-natural-fluido' WHERE id = 584;
UPDATE foods SET name = 'Extrato de soja em pó', slug = 'extrato-de-soja-em-po' WHERE id = 585;
UPDATE foods SET name = 'Tofu', slug = 'tofu' WHERE id = 586;
UPDATE foods SET name = 'Tremoço cru', slug = 'tremoco-cru' WHERE id = 587;
UPDATE foods SET name = 'Tremoço em conserva', slug = 'tremoco-em-conserva' WHERE id = 588;
UPDATE foods SET name = 'Amêndoa torrada salgada', slug = 'amendoa-torrada-salgada' WHERE id = 589;
UPDATE foods SET name = 'Castanha de caju torrada salgada', slug = 'castanha-de-caju-torrada-salgada' WHERE id = 590;
UPDATE foods SET name = 'Castanha-do-pará crua', slug = 'castanha-do-para-crua' WHERE id = 591;
UPDATE foods SET name = 'Coco cru', slug = 'coco-cru' WHERE id = 592;
UPDATE foods SET name = 'Farinha de mesocarpo de babaçu crua', slug = 'farinha-de-mesocarpo-de-babacu-crua' WHERE id = 593;
UPDATE foods SET name = 'Semente de gergelim', slug = 'semente-de-gergelim' WHERE id = 594;
UPDATE foods SET name = 'Semente de linhaça', slug = 'semente-de-linhaca' WHERE id = 595;
UPDATE foods SET name = 'Pinhão cozido', slug = 'pinhao-cozido' WHERE id = 596;
UPDATE foods SET name = 'Pupunha cozida', slug = 'pupunha-cozida' WHERE id = 597;
UPDATE foods SET name = 'Noz crua', slug = 'noz-crua' WHERE id = 598;

COMMIT;
